services:
  auth:
    image: a-auth
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Port=5432;Database=User;User Id=dev;Password=dev;
    ports:
      - 5001:80
    extra_hosts:
    - "host.docker.internal:host-gateway"
  
  api:
    image: a-server
    environment:
      - ConnectionStrings__TodoContext=User ID=dev;Password=dev;Host=host.docker.internal;Port=5432;Database=organize;
      - Authentication__Schemes__Bearer__ValidAudiences__0=http://localhost:5001/resources
      - Authentication__Schemes__Bearer__AuthAuthority=http://auth/resources
      - Authentication__Schemes__Bearer__MetaDataAddress=http://auth/.well-known/openid-configuration
      - Authentication__Schemes__Bearer__RequireHttpsMetaData=false
      - Authentication__Schemes__Bearer__GetClaimsFromUserInfoEndpoint=true
    ports:
      - 5002:8080
    extra_hosts:
    - "host.docker.internal:host-gateway"

