on:
  push:
    branches: [ "main" ]
env:
  SSH_KEY: ${{ secrets.PRIVATE_KEY }}
  APP_HOST: ${{ secrets.HOST }}
  DB_PASSWORD: ${{ secrets.DBPASSWORD }}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore ./Server/OrganizeApi.csproj
      - name: Build
        run: dotnet publish --no-restore ./Server/OrganizeApi.csproj -o ./Server/dist
      - name: Zip
        run: zip -r serverbuild.zip ./Server/dist
      - name: Build migrations
        run: |
          dotnet tool restore
          cd ./Server
          dotnet ef  migrations bundle --self-contained -r linux-x64
          cd ..
      - name: Push to host
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_KEY" | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          scp -o StrictHostKeyChecking=no serverbuild.zip ./Server/efbundle ./serversetup.sh luke@"$APP_HOST":~
          ssh -o StrictHostKeyChecking=no luke@"$APP_HOST" "export DBPASSWORD='${{ secrets.DBPASSWORD }}';cd ~; chmod 777 serversetup.sh; ./serversetup.sh;"
          

          
      

    
