on:
  push:
    branches: [ "main" ]
env:
  SSH_KEY: ${{ secrets.PRIVATE_KEY }}
  APP_HOST: ${{ secrets.HOST }}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore ./Auth/AuthServer.csproj
      - name: Build
        run: dotnet publish --no-restore ./Auth/AuthServer.csproj -o ./Auth/dist
      - name: Zip
        run: zip -r authbuild.zip ./Auth/dist
      - name: Push to host
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_KEY" | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          scp -o StrictHostKeyChecking=no authbuild.zip luke@"$APP_HOST":./authbuild.zip
          ssh -o StrictHostKeyChecking=no luke@"$APP_HOST" "cd ~; rm -r ./auth; unzip ./authbuild.zip -d ./;"
        