on: 
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deployment_job:
    runs-on: ubuntu-latest
    name: Deployment Job
    environment: production
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: npm install, build, and test
      run: |
        npm install ./UI
        npm --prefix ./UI run build --if-present

    - name: List folder
      run: ls ./UI/build
     
    - name: SSH
      uses: ErenKrt/ssh-push@main
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        source: "./UI/build/"
        outdir: ./app/test/
