on: 
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deployment_job:
    runs-on: ubuntu-latest
    name: Deployment Job
    environment: prod
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: npm install, build, and test
      run: |
        npm install ./UI
        npm --prefix ./UI run build --if-present

    - name: List folder
      run: ls ./UI/build
     
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./UI/build/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "./test"
          EXCLUDE: "/dist/, /node_modules/"
