on: 
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SSH_KEY: ${{ secrets.PRIVATE_KEY }}
jobs:
  deployment_job:
    runs-on: ubuntu-latest
    name: Deployment Job
    environment: prod
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: yarn install, build, and test
      run: |
        cd ./UI
        yarn install 
        yarn run build

    - name: List folder
      run: ls ./UI/build
     
    - name: SSH
      run: |
         apt install openssh-client
         eval $(ssh-agent -s)
         echo SSH_KEY | tr -d '\r' | ssh-add -
         mkdir -p ~/.ssh
         chmod 700 ~/.ssh
         ssh -o StrictHostKeyChecking=no luke@161.35.41.90 "cd ~; touch test.txt"
