name: branch-test

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
env:
  REPO: ${{ github.repository }}
  PR_NO: ${{ github.event.issue.number }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  ad-hoc: 
    runs-on: ubuntu-latest
    name: a test 
    steps:
    - id: 'print-env'
      run: echo '${{ toJSON(github) }}'
    - id: 'get-branch'
      run: echo "$(gh pr view 2 --repo $REPO --json headRefName --jq '.headRefName')"
     
    - id: 'print'
      run: echo "::notice ${{ steps.get-branch.outputs.branch  }}"
      
