name: branch-test

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  ad-hoc: 
    runs-on: ubuntu-latest
    name: a test 
    steps:
    - id: 'print-env'
      run: | 
          echo "$GITHUB_HEAD_REF"
          echo "$GITHUB_REF"
          echo "$GITHUB_PATH"
          echo "$GITHUB_REF_NAME"
          echo "$GITHUB_REPOSITORY"
    - id: 'get-branch'
      run: echo "branch=$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')" >> $GITHUB_OUTPUT
      env:
        REPO: ${{ github.repository }}
        PR_NO: ${{ github.event.issue.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - id: 'print'
      run: echo "::notice ${{ steps.get-branch.outputs.branch  }}"
      
